Generate classes in MultifileClassCodegen exactly the same as in PackageCodegen
Two known issues with generateNonPartClassDeclarations that was here
before were the fact that we didn't sort sealed classes and its
subclasses which led to NoSuchMethodError (KT-27097), and the fact that
the we didn't skip expect classes which led to duplicate JVM class name
diagnostic (KT-30843)

 #KT-27097 Fixed
 #KT-30843 Fixed